### ISSUE TITLE
Can't do rename

### ISSUE THREAD

**Issue by DanielSundberg** [hax/refactor#4]
First I had to struggle to find and available keyboard mapping, ctrl-alt-r was occupied by "window:reload" which made it very difficult to find out what was going on.

When I did find a shortcut key I can't get it to do a rename at all. When I press the keyboard shortcut nothing happens.

Is there anything I can do to help debug this problem?

**Comment by MatejKafka** [comment]
Same issue here

**Comment by hax** [comment]
Currently only JavaScript is supported (coffeescript support is no maintainer now), so if you think there are some cases should be able to rename but not works, please paste a code snippet here. Thank you!

**Comment by DanielSundberg** [comment]
I've got it working now by installing refactor and js-refactor again. Then I added the following in my keymap file:

```
'atom-text-editor:not(.mini)':
  'ctrl-alt-shift-e': 'refactor:rename'
```

Now when I press ctrl-alt-shift-e all words matching that at my cursor get selected and I can start typing to rename. It was not obvious that this was how it was supposed to work. Maybe this was the way it worked the last time I tried this?

I know you've got an animation in the readme but it's not very easy to see what's going on.

Also, you should really change the default shortcut to something that is not occupied by default. It should be a shortcut similar to something found in other editors.

**Comment by DanielSundberg** [comment]
Almost immediately I get another error: https://github.com/hax/js-refactor/issues/1

I will uninstall once again.

**Comment by hax** [comment]
@DanielSundberg The default keybinding of "window:reload" is "ctrl-alt-cmd L", so it seems you customized it. But anyway, you could suggest a shortcut which you think better than "ctrl-alt-r" in a new issue :grinning:

**Comment by DanielSundberg** [comment]
On windows "ctrl-alt-r" is default for "window:reload".

**Comment by hax** [comment]
@DanielSundberg Oh, my mistake. Do you have any suggestion? :panda_face:

**Comment by DanielSundberg** [comment]
Sorry, I don't have any suggestions. F2 or "ctrl-r, ctrl-r" would have worked but both seem to be occupied in Atom (ctrl-r is bound to "symbols-view:toggle-file-symbols" which probably disqualifies "ctrl-r,ctrl-r"). Finding good key bindings is very difficult...

**Comment by hax** [comment]
I just published new version (0.6.0) which include many fixes and improvements (eg. experimental support of babel and jsx). Please update and check :smile:

**Comment by Kurtas** [comment]
Still not working on Windows, because of bad mapping ( "ctrl-alt-r" is default for "window:reload"). I don't know but Atom ignore my user setting for other keys maps.

**Comment by damianh** [comment]
:+1: to changing to F2

**Comment by DanielSundberg** [comment]
F2 is mapped to 'bookmarks:jump-to-next-bookmark' on Windows....

**Comment by damianh** [comment]
so it is, hmm

**Comment by ZoRDoK** [comment]
similar issue on linux
rebinding but not work

solved:
'body':
  'ctrl-alt-r': 'unset!'
'atom-text-editor:not(.mini)':
  'ctrl-alt-r': 'refactor:rename'

  And second problem: not work if file a not compileable

**Comment by hax** [comment]
I found that ternjs plugin use `ctrl-alt-c` for rename. ( https://github.com/tststs/atom-ternjs/blob/master/keymaps/atom-ternjs.cson )
Don't know whether it's a good choice.

**Comment by rafaelcn** [comment]
Hello @hax , I opened a [thread](https://discuss.atom.io/t/refactor-is-not-working-at-all/22645) on atom discussion about this, can you check it out? It looks like the Refactor package is not _reacting to atom commands_ as leedohm said.

I'm using linux currently if it helps.

**Comment by hax** [comment]
@rafaelcn Sorry, rename only works for variable not method/property. The latter need more complex analyze of AST.

**Comment by rafaelcn** [comment]
So we will need to make improvements! :smile: 
I'm willing to help.

**Comment by rafaelcn** [comment]
And I had to change the default keystroke, on linux, `ctrl-alt-r` reloads Atom.

**Comment by hax** [comment]
Help is welcome :smiley_cat: 

I will release a new version which change the default keystroke soon.

**Comment by PhiLhoSoft** [comment]
I chose `alt-shift-r`, free on my system, keeping the R mnemonic. Some package creators just provide an empty keybinding map, as finding a sensible shortcut across Atom versions, locale changes (via the `keyboard-localization` package) and installed packages is becoming increasingly hard!

**Comment by Norfeldt** [comment]
Also an windows user.. I couldn't make this work, but found out having installed the "Highlight Selected" package and using CTRL+D first highlights all instances. Repeating CTRL+D allows renaming.. 

Not having this package also allows renaming, but only for instances occurring after the selected and not the ones before. 

I would however like to use this package instead since I notice that it also highlights all instances without having to double click or CTRL+D.

**Comment by kili-ilo** [comment]
@hax any news on the new version? on Windows it's still broken

**Comment by PhiLhoSoft** [comment]
@jvanbrug What is "broken"? I use this package on Windows for quite some time, and it works rather fine, overall.

**Comment by kili-ilo** [comment]
@PhiLhoSoft with `js-refactor`, even after binding a shortcut other than `ctrl-alt-r`, I couldn't get it to ever refactor a variable - it could totally be my fault, but I assume it has something to do with @Norfeldt's problem

**Comment by Norfeldt** [comment]
I have MANY packages installed... like autocomplete and Emmett.. could very well be some sort of collision. 
@philhsoft what packages do you have?

**Comment by PhiLhoSoft** [comment]
My list of plugins is at https://gist.github.com/PhiLhoSoft/b61b3e3d13ebd802bb08
As said, Ctrl+Alt+R is bound to "reload Atom", you might want to change the shortcut.

**Comment by Davilink** [comment]
I finally succeed to bypass the window:reload config with this (in the keymap config file): 

```
'body':
  'f5': 'window:reload'
  'ctrl-alt-r' : 'abort!'
```

And refactor need the js-refactor package.

**Comment by mindjuice** [comment]
This wasn't working for me either.  The problem was that I was trying to rename in ES6 code, which it apparently doesn't support.

Switching to a plain JS file worked.

**Comment by hax** [comment]
@mindjuice We already have basic ES6 support. Could you help me to find which part of your ES6 code cause the problem?

**Comment by mindjuice** [comment]
Oh...sorry for jumping to conclusions.

Looks like it just either needed me to restart Atom, or perhaps just close all active files and reopen them.

I was able to get it working with `const` and `let` now.

Would be nicer if it "just worked" after installing it, if possible.

One thing is that the highlighting is pretty glitchy.  Sometimes a highlight stays after I'm no longer on a given variable, and if I press `ctrl-alt-r` repeatedly, I get multiple highlight rects overlapping and their alphas build up to a brighter and brighter color.

I can file a separate issue for this.

**Comment by AntonioRedondo** [comment]
Same issue here with 0.6.0 version. If this is still alive I suggest `shift+f6` shortcut (the same than JetBrains/IntelliJ products). In the meanwhile and as suggested by @Norfeldt it looks like with the `highlith-selected` package and after pressing `ctlr+d` makes the rename variable job very well.

**Comment by hax** [comment]
Closed. Further discussion of keybinding issues could goto #22 .

**Comment by IPWright83** [comment]
I've tried re-binding (which I think I've done), but it just doesn't seem to do anything. I've produced a very minimal example which doesn't seem to work either within, or across files:

_A.js_

```
class Foo {
  bar() { console.log("bar"); }
}

let b = new Foo();
b.bar();
```

_B.js_

```
import {Foo} from './A';

let f = new Foo();
f.bar();
```

**Comment by hax** [comment]
Renaming across files is out of current scope of this project. (It require read and analysis all js files in project and will be very heavy, just like a true IDE.)

But at least when you rename `Foo` to `Bar` in `B.js`, it will be refactor to:

``` js
import {Foo as Bar} from './A';

let f = new Bar();
f.bar();
```

And you should add `export` in `A.js`.

**Comment by IPWright83** [comment]
@hax but in file _A.js_ when I attempt to rename the `bar` function, nothing happens when I press the bound shortcut, so I can't even rename within the same file?

**Comment by hax** [comment]
@IPWright83 Could you try latest versions? (js-refactor 0.7.3)

**Comment by Tokimon** [comment]
I have the same problem.

I have just installed js-refactor 0.10.0 and I still can't rename my variables etc. in my JS.
Normally I work in ES6, so I was wondering if that was the problem, but it didn't even work with this basic example:

``` javascript
function f(a) {
  a.b = 'c';
}
```

When I call the command `refactor:rename` (trying to refactor `a`) nothing happens.

### What I have tried
- Disabling _'window:reload'_ (which annoyed me)  
  By adding this to my keymap.cson:  

```
  'body':
    'ctrl-alt-r': 'unset!'
```
- Using the shortcut **ctrl-alt-r** and verified in **Key Binding Resolver** that it actually executed the command.
- Calling the command directly from the **command palette**
- Reinstalling **refactor** and **js-refactor**
- Restarting atom (before and after reinstall)

### My installed packages

atom-beautify@0.29.13
atom-react-native-autocomplete@0.0.27
autoclose-html@0.23.0
babel-react-syntax@1.2.0
blame@0.10.0
color-picker@2.2.2
custom-title@1.0.1
docblock-format-helper@0.3.0
docblockr@0.8.7
double-click-tree-view@1.1.0
emmet@2.4.3
emmet-snippets-compatibility@1.0.6
es-identifier-highlight@0.4.0
file-icons@1.7.24
imdone-atom@2.0.14
js-refactor@0.7.3
keyboard-localization@1.4.18
language-apache@1.7.0
language-babel@2.48.0
language-generic-config@1.2.0
language-javascript-jsx@0.3.7
language-stylus@0.2.0
linter@1.11.18
linter-eslint@8.0.0
linter-htmlhint@1.3.1
linter-js-yaml@1.2.5
linter-json-lint@0.1.1
minimap@4.25.6
minimap-cursorline@0.2.0
minimap-find-and-replace@4.5.1
minimap-linter@1.6.0
minimap-pigments@0.2.1
navigate@0.1.16
php-cs-fixer@2.5.9
php-integrator-autocomplete-plus@1.1.5
php-integrator-base@1.2.6
php-integrator-call-tips@1.1.1
php-integrator-linter@1.2.1
php-integrator-navigation@1.0.3
php-integrator-symbol-viewer@0.6.4
php-integrator-tooltips@1.0.4
php-twig@4.0.0
project-viewer@0.3.25
refactor@0.10.0
seti-ui@1.3.2
Sublime-Style-Column-Selection@1.7.2
tabs-to-spaces@1.0.2
turbo-javascript@1.4.0

**Comment by jhegedus42** [comment]
Does not work, using vi plugin...., without vi, it works...

**Comment by hax** [comment]
@jhegedus42 Do you mean vim-mode plugin?
